apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: orders-microservice-secret
  namespace: statex-apps
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: orders-microservice-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/prod/orders-microservice
        property: JWT_SECRET
