apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: orders-microservice-secret
  namespace: statex-apps
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: orders-microservice-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/prod/orders-microservice
        property: DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/prod/auth-microservice
        property: JWT_SECRET
    - secretKey: JWT_TOKEN
      remoteRef:
        key: secret/prod/orders-microservice
        property: JWT_TOKEN
    - secretKey: WAREHOUSE_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/orders-microservice
        property: WAREHOUSE_SERVICE_TOKEN
    - secretKey: CATALOG_INTERNAL_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/auth-microservice
        property: CATALOG_INTERNAL_SERVICE_TOKEN

    - secretKey: FLIPFLOP_INTERNAL_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/flipflop-service
        property: ORDERS_SERVICE_TOKEN
    - secretKey: ALLEGRO_INTERNAL_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/allegro-service
        property: JWT_TOKEN
    - secretKey: AUKRO_INTERNAL_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/aukro-service
        property: JWT_TOKEN
    - secretKey: BAZOS_INTERNAL_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/bazos-service
        property: JWT_TOKEN
    - secretKey: HEUREKA_INTERNAL_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/heureka-service
        property: JWT_TOKEN
    - secretKey: CLIPLOT_ORDERS_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/cliplot
        property: ORDERS_SERVICE_TOKEN
    - secretKey: PAYMENTS_INTERNAL_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/payments-microservice
        property: JWT_TOKEN
    - secretKey: INVOICES_INTERNAL_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/invoices-microservice
        property: ORDERS_SERVICE_TOKEN
