apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: orders-microservice-secret
  namespace: statex-apps
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: orders-microservice-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/prod/orders-microservice
        property: DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/prod/auth-microservice
        property: JWT_SECRET
    - secretKey: JWT_TOKEN
      remoteRef:
        key: secret/prod/orders-microservice
        property: JWT_TOKEN
    - secretKey: WAREHOUSE_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/orders-microservice
        property: WAREHOUSE_SERVICE_TOKEN
    - secretKey: CATALOG_INTERNAL_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/catalog-microservice
        property: CATALOG_INTERNAL_SERVICE_TOKEN
